config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses
  resources :users, only: [:index]
  root 'home#index'
  get 'activity', to: 'home#activity'
  get 'privacy_policy', to: 'home#privacy_policy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  include PublicActivity::Model
  tracked owner: Proc.new { |controller, model| controller.current_user }
  
  belongs_to :user
  validates :title, :level, :language, presence: true
  validates :description, presence: true, length: { :minimum => 5 }
  validates :short_description, presence: true, length: { :minimum => 5 }
  validates :price, presence: true
  has_rich_text :description

  extend FriendlyId
  friendly_id :title, use: :slugged
  
  LANGUAGES = [:"English", :"French", :"Spanish"]
  def self.languages
    LANGUAGES.map { |language| [language, language] }
  end

  LEVELS = [:"Beginner", :"Intermediate", :"Advanced"]
  def self.levels
    LEVELS.map { |language| [language, language] }
  end
  
  def to_s
    title
  end
  # friendly_id :generated_slug, use: :slugged
  # def generated_slug
  #   require 'securerandom'
  #   @random_slug ||= persisted? ? friendly_id : SecureRandom.hex(4)
  # end

  # def to_s
  #   slug
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable, :confirmable
         
  has_many :courses

  def to_s
    email
  end

  def username
    email.split('@').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include PublicActivity::StoreController
  before_action :authenticate_user!
  before_action :set_global_variables, if: :user_signed_in?

  def set_global_variables
    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    # if params[:title]
    #   @courses = Course.where('title ILIKE ?', "%#{params[:title]}%")
    # else
      #@courses = Course.all
      # @q = Course.ransack(params[:q])
      # @courses = @q.result.includes(:user)
    # end
      @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
      @courses = @ransack_courses.result.includes(:user)
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)
    @course.user = current_user
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :short_description, :language, :level)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @courses = Course.all.limit(3)
    @latest_courses = Course.all.limit(3).order(created_at: :desc)
  end

  def activity
    @activities = PublicActivity::Activity.all
  end

  def privacy_policy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    #@users = User.all.order(created_at: :desc)

    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/courses/_course.html.haml
.card
  .card-header
    .fa.fa-graduation-cap
    = link_to course.title, course_path(course)
  .card-body
    %small= simple_format(course.short_description)
  .card-footer
    .text-center
      = number_to_currency(course.price)
  .card-footer
    .row
      .col-md-6
        .fa.fa-globe-africa
        = course.language
      .col-md-6
        .text-right
          .fa.fa-signal
          = course.level
  .card-footer
    .row
      .col-md-6
        .far.fa-clock
        = course.created_at.strftime('%d-%b-%y')
      .col-md-6
        .text-right
          .fa.fa-chalkboard-teacher
          = course.user.username
  .card-footer
    = link_to 'Show', course, class: 'btn btn-sm btn-primary'
    = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning'
    = link_to 'Delete', course, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-sm btn-danger'

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.input :description, as: :rich_text_area
    %small= f.error :description, class: 'text-danger'
    = f.input :short_description
    = f.input :language, collection: Course.languages, include_blank: true 
    = f.input :level, collection: Course.levels, include_blank: true 
    = f.input :price

  .form-actions
    = f.button :submit

app/views/courses/edit.html.haml
.card.mb-3
  .card-header 
    %h1 Editing course
  .card-body
    = render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
%h3.mb-5
  .text-center
    Courses
    .badge.badge-info
      = @courses.count

.courses-courses-container
  .row
    .col-md-2
      .mt-4.mb-2
        = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
          = f.label :title
          = f.search_field :title_cont, placeholder: 'Ruby', class: 'form-control form-control-sm'
          .mt-2
          = f.label :description
          = f.search_field :short_description_cont, placeholder: 'Best course', class: 'form-control form-control-sm'
          .mt-2
          .mt-2
          = f.label :price
          = f.search_field :price_eq, placeholder: '100', class: 'form-control form-control-sm'
          .mt-2
          = f.label :teacher
          = f.search_field :user_email_cont, placeholder: 'Email', class: 'form-control form-control-sm'
          .mt-2
          = f.label :language
          = f.select :language_cont, Course.languages, include_blank: true, class: 'custom-select'
          .mt-2
          = f.label :level
          = f.select :level_cont, Course.levels, include_blank: true, class: 'custom-select'
          .mt-2 
          = f.submit
        .mt-2
        = link_to courses_path, class:"btn btn-sm btn-secondary" do
          .fa.fa-sync
    .col-md-10
      .card-columns
        = render @courses

app/views/courses/new.html.haml
.card.mb-3
  .card-header
    %h1 New course
  .card-body
    = render 'form'

= link_to 'Back', courses_path, class:'mt-3'

app/views/courses/show.html.haml
= link_to 'Courses', courses_path
\/
= link_to @course.title, course_path(@course)

= render @course

app/views/home/activity.html.haml
%h3.mb-5
  .text-center
    Activity
    .badge.badge-info
      = @activities.count

%ul.list-group
  - @activities.each do |activity|
    %li.list-group-item
      -# = activity.id
      = activity.trackable_type
      -# = activity.trackable_id
      = link_to activity.trackable, activity.trackable
      was
      = activity.key.split(".").last + "d"
      -# = activity.parameters
      by
      = activity.owner.username

app/views/home/index.html.haml
.jumbotron
  .display-4
    What do you want to learn today?
  - if user_signed_in?
    .form-inline.my-4
    = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
      .input-group
        = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 200px; border: 1px solid #fff;', placeholder: "Find a course"
        %span.input-group-append
          %button.btn.btn-sm.btn-primary{type: "submit"}
            %span.fa.fa-search{"aria-hidden": "true"}
.card-group
  .card.card-body
    %h2
      .fa.fa-graduation-cap
    = Course.count
    online courses
    .row
    Explore a variety of fresh topics
  .card.card-body
    %h2
      .fa.fa-chalkboard-teacher
      /.fa.fa-brain
    = Course.distinct.count(:user_id)
    expert instructors
    .row
    Find the right instructor for you
  .card.card-body
    %h2
      .fa.fa-user-graduate
    = User.count
    active learners
    .row
    Join the knowledge sharing community
  .card.card-body
    %h2
      .fa.fa-infinity
    Lifetime access
    .row
    Learn on your schedule

.home-courses-container
  %hr
  %h3
    Popular courses
  .card-columns
    = render @courses
  %hr
  %h3
    Top rated courses
  .card-columns
    = render @courses
  %hr
  %h3
    Latest courses
  .card-columns
    = render @latest_courses

app/views/home/privacy_policy.html.haml
%h1 StaticPages#privacy_policy
= link_to 'Home', root_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RailsGemsBootcamp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:http-equiv => "X-UA-Compatible", :content => "IE=edge,chrome=1"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    = render "shared/navbar"
    = render "shared/flashes"
    .container-fluid.my-5
      = yield
    = render "shared/footer"

app/views/shared/_flashes.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", role: "alert"}
      %button.close{"aria-hidden": "true", "data-dismiss": "alert", "type": "button"} x
      = content_tag :div, msg, id: "flash#{name}"

app/views/shared/_footer.html.haml
%footer
  .container-fluid
    .row.py-5
      .col-md-4
        Copyright
        c
        = Time.now.year
        CoursePlatform Sp. z o.o.
        .row
        .fa.fa-envelope
        = mail_to 'support@rubygems.com'
        .row
      .col-md-4
        Privacy policy
        .row
        Terms & conditions
      .col-md-4
        About us
        .row
        = link_to 'Teach on CoursePlatform', new_course_path

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark
  %a.navbar-brand{:href => "/"} Rubygems
  %button.navbar-toggler{"aria-controls" => "navbarSupportedContent", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarSupportedContent", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarSupportedContent.collapse.navbar-collapse
    - if current_user
      %ul.navbar-nav.mr-auto
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(root_path)}"}
          = link_to root_path, class: 'nav-link' do
            .fa.fa-home
            Home
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(courses_path)}"}
          = link_to courses_path, class: 'nav-link' do
            .fa.fa-graduation-cap
            Courses
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(new_course_path)}"}
          = link_to new_course_path, class: 'nav-link' do
            .fa.fa-plus
            New Course
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(users_path)}"}
          = link_to users_path, class: 'nav-link' do
            .fa.fa-users
            Users
      = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
        .input-group
          = f.search_field :title_cont, class: 'form-control-sm', style: 'float: left; width: 150px; border: 1px solid #fff;', placeholder: "Search"
          %span.input-group-append
            %button.btn.btn-sm.btn-primary{type: "submit"}
              %span.fa.fa-search{"aria-hidden": "true"}
      %ul.navbar-nav.mr-right
        %li.nav-item{class: "#{'active font-weight-bold' if current_page?(activity_path)}"}
          = link_to activity_path, class: 'nav-link' do
            .fa.fa-bell
            Activity
        %li.nav-item.dropdown
          %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            %b= current_user.email
          .dropdown-menu.dropdown-menu-right{"aria-labelledby" => "navbarDropdown"}
            = link_to edit_user_registration_path, class: "dropdown-item" do
              .fa.fa-cog
              %b Account settings
            = link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do
              .fa.fa-sign-out-alt
              %b Sign out
    - else
      %ul.navbar-nav
        %li.nav-item= link_to 'Sign Up', new_user_registration_path, class: 'nav-link'
        %li.nav-item= link_to 'Log In', new_user_session_path, class: 'nav-link'

app/views/users/_user.html.haml
.card
  .card-header
    .fa.fa-user
    = user.email
  .card-footer
    Signed Up
    = time_ago_in_words(user.created_at)
    ago
    .row
  .card-footer
    = 'sign_in_count'.humanize
    = user.sign_in_count
    .row
    = 'current_sign_in_at'.humanize
    = user.current_sign_in_at
    .row
    = 'last_sign_in_at'.humanize
    = user.last_sign_in_at
    .row
    = 'current_sign_in_ip'.humanize
    = user.current_sign_in_ip
    .row
    = 'last_sign_in_ip'.humanize
    = user.last_sign_in_ip
  .card-footer
    Confirmed email?
    - if user.confirmed_at.present?
      .badge.badge-success Yes
    - else
      .badge.badge-danger No

app/views/users/index.html.haml
%h3.mb-5
  .text-center
    Users
    .badge.badge-info
      = @users.count

.card-columns
  = render @users

.form-inline.mt-4.mb-2
  = search_form_for @q do |f|
    = f.search_field :email_or_sign_in_count_eq, placeholder: 'email or sign in count'
    = f.submit
  .ml-2
  = link_to users_path, class:"btn btn-sm btn-secondary" do
    .fa.fa-sync

%table.table.table-bordered
  %thead
    %tr
      %th id 
      %th= sort_link(@q, :email)
      %th created_at 
      %th= 'sign_in_count'.humanize 
      %th= 'current_sign_in_at'.humanize
      %th= 'last_sign_in_at'.humanize
      %th= 'current_sign_in_ip'.humanize
      %th= 'last_sign_in_ip'.humanize
  %tbody
    - @users.each do |user|
      %tr
        %td= user.id
        %td= user.email
        %td= user.created_at
        %td= user.sign_in_count
        %td= user.current_sign_in_at
        %td= user.last_sign_in_at
        %td= user.current_sign_in_ip
        %td= user.last_sign_in_ip